PARAGRAPH='Paragraph'
BULLET_LIST='Bullet List'
NUMBERED_LIST='Numbered List'
TABLE='Table'
TABLE_AS_PLAIN_TEXT='Table format that can be copied to txt file without any formatting issue'
CSV='Csv'
MARKDOWN='Markdown'
CODE_BLOCK='Code Block'
JSON='JSON'
YAML='YAML'
XML='XML'
TEXT='Text'
DOCUMENT_STYLE='Heading in Bold and Underlined. Points in numbers'
TWEET='Tweet'
POST='Post'
EMAIL='Email'
DIALOG='Dialog'
SCRIPT='Script'
SCREENPLAY='Screenplay'
QNA='Q&A'
FAQ='FAQ'
CHECKLIST='Checklist'
BDD='BDD'
HTML='''
Html Format
Only return body-level HTML like <h1>, <p>, <b>, <u>, <ul>, <li>.
Do not include <html>, <head>, or <style> tags.
Do not wrap it in triple quotes or code blocks like ```html or \'''html. Just return the raw HTML string.
'''